version: "3"
services:
  mongo:
    image: mongo
    container_name: "mongo_db"
    restart: "always"
    volumes:
      - mongodata:/data/db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
    mongodata: